name: CI

on:
  push:
    branches: [main, master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - ubuntu-24.04-riscv
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Show toolchain
        run: rustc -Vv

      - name: Check test build
        run: cargo test --no-run

      - name: Test
        run: cargo test

      - name: Test internals feature
        run: cargo test --features __INTERNALS_DO_NOT_USE
